services:
  backend:
    build: ./backend
    container_name: mrssh-v4-backend
    network_mode: host
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /opt/mrssh-backups:/opt/mrssh-backups
      - /opt/mrssh-agent/mrssh.db:/opt/mrssh-agent/mrssh.db:rw
